### ISSUE TITLE
✅ Homework Feedback #3

### ISSUE THREAD

**Issue by cmota** [brayandm/Homework1#1]
Hello 👋,

Let me start by saying that I really liked that you dive-in directly in Compose to do this exercise 🙌. 

The UI is almost perfect! I've only noticed a minor issue, which is that you've used a border on the card instead of having a divider. 

This makes that the card has a border around it instead of having just a line at the end of each section.

One solution to achieve this could be for instance:

```
Divider(thickness = 1.dp, color = Color.LightGray)
```

Keep up with the good work! 🙌

### Grade

98/100

### Suggestions for improvement

I'm going to write a couple of suggestions for improvement, but don't worry, these are really minor 🙂 

* Looking at the imports on your **MainActivity.kt** I'm seeing that some are not used in the project. When an import is not used, Android Studio changes its color to grey. Although, this doesn't have any impact on your code, it's always a good approach to only have the ones that you're using declared.

* I would move the `Homework1Theme` declaration from being inside `Screen` to be after `setContent`. Since `Screen` is already drawing the screen, I would make this separation

* When you declare a **Composable** and don't define any property - for instance, `Card` on line 52 - you can remove the parenthesis, since they're not doing anything on the code. 

* You've declared variables as `var` when you can declare them as `val`. For instance, from line 150-152,  `width`, `height`, and `padding` are declared as `var` when their values never changes. In this scenarios, you should declare them as `val`. Remember that `val` means **value** (=immutable)  and `var` **variable** (=variable).

**Comment by brayandm** [comment]
Divider added :)
